### ISSUE TITLE
Template de Latex

### ISSUE THREAD

**Issue by tomastrivino** [IIC1253/IIC1253-2023-2#3]
Hola,
en la tarea 1 sale lo siguiente:
<img width="911" alt="image" src="https://github.com/IIC1253/IIC1253-2023-2/assets/98418205/cbf1af80-3d06-4fad-9ca4-2b2dde0280ed">

El problema es que hasta el momento (quizás por despistado) no he encontrado la plantilla que están solicitando. ¿Saben si está subida y dónde? 

Gracias.
P.D. No me permite agregar labels.

**Comment by cicarrasco5** [comment]
Hola Tomás,
ya subimos la template a la plataforma de Canvas de las secciones 1, 2 y 3 en las carpetas "Tareas", mientras que la sección 4 puede acceder a ella mediante el drive del curso en la carpeta con el mismo nombre.
Sobre las labels ya está solucionado mediante plantillas de issues de preguntas que vienen previamente etiquetadas, la explicación de uso también se actualizó en el repo.
Cualquier duda pueden escribirnos!
